name: Nightwatch Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    defaults:
      run:
        working-directory: /home/runner/work/PIE_tools/PIE_tools/nightwatch
  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package.json'

    - uses: actions/download-artifact@v3
      with:
        name: logs
        path: /home/runner/work/PIE_tools/PIE_tools/nightwatch/logs/tests/snow_run_command_chromedriver.log

    #- run: find /home/runner/
    - run: ls -ltr /opt/google/chrome
    - run: /opt/google/chrome/google-chrome --version
    - run: /opt/google/chrome/chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
    - run: mkdir custom-assertions custom-commands page-objects examples
      working-directory: /home/runner/work/PIE_tools/PIE_tools/nightwatch
    - run: mkdir -p /home/runner/work/PIE_tools/PIE_tools/nightwatch/node_modules/chromedriver/lib/chromedriver
    - run: cp /usr/local/share/chromedriver-linux64/chromedriver /home/runner/work/PIE_tools/PIE_tools/nightwatch/node_modules/chromedriver/lib/chromedriver/. 
    - run: npm ci 
    # # - run: sudo apt-get install xvfb 
    # # - run: xvfb-run --auto-servernum npm test -- --env chrome tests/snow_run_command.js
    # - run: ps -elf | grep chrome
    # - run: /usr/bin/google-chrome --version
    - run: /usr/local/share/chromedriver-linux64/chromedriver --version
    - run: /home/runner/work/PIE_tools/PIE_tools/nightwatch/node_modules/chromedriver/lib/chromedriver/chromedriver --version
    - run: npx nightwatch --config nightwatch.conf.js tests/snow_run_command.js
        #   working-directory: /home/runner/work/PIE_tools/PIE_tools/nightwatch
